/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRecyclingRouteImport } from './routes/about-recycling'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminHomeRouteImport } from './routes/admin/home'
import { Route as AdminHistoryRouteImport } from './routes/admin/history'
import { Route as AdminGameRouteImport } from './routes/admin/game'
import { Route as AdminContactRouteImport } from './routes/admin/contact'
import { Route as AdminCareersRouteImport } from './routes/admin/careers'
import { Route as AdminAboutRecyclingRouteImport } from './routes/admin/about-recycling'
import { Route as AdminAboutRouteImport } from './routes/admin/about'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRecyclingRoute = AboutRecyclingRouteImport.update({
  id: '/about-recycling',
  path: '/about-recycling',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/admin/home',
  path: '/admin/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/admin/history',
  path: '/admin/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGameRoute = AdminGameRouteImport.update({
  id: '/admin/game',
  path: '/admin/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/admin/contact',
  path: '/admin/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/admin/careers',
  path: '/admin/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAboutRecyclingRoute = AdminAboutRecyclingRouteImport.update({
  id: '/admin/about-recycling',
  path: '/admin/about-recycling',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/admin/about',
  path: '/admin/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-recycling': typeof AboutRecyclingRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/history': typeof HistoryRoute
  '/services': typeof ServicesRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/about-recycling': typeof AdminAboutRecyclingRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-recycling': typeof AboutRecyclingRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/history': typeof HistoryRoute
  '/services': typeof ServicesRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/about-recycling': typeof AdminAboutRecyclingRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-recycling': typeof AboutRecyclingRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/history': typeof HistoryRoute
  '/services': typeof ServicesRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/about-recycling': typeof AdminAboutRecyclingRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-recycling'
    | '/careers'
    | '/contact'
    | '/history'
    | '/services'
    | '/admin/about'
    | '/admin/about-recycling'
    | '/admin/careers'
    | '/admin/contact'
    | '/admin/game'
    | '/admin/history'
    | '/admin/home'
    | '/admin/services'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-recycling'
    | '/careers'
    | '/contact'
    | '/history'
    | '/services'
    | '/admin/about'
    | '/admin/about-recycling'
    | '/admin/careers'
    | '/admin/contact'
    | '/admin/game'
    | '/admin/history'
    | '/admin/home'
    | '/admin/services'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-recycling'
    | '/careers'
    | '/contact'
    | '/history'
    | '/services'
    | '/admin/about'
    | '/admin/about-recycling'
    | '/admin/careers'
    | '/admin/contact'
    | '/admin/game'
    | '/admin/history'
    | '/admin/home'
    | '/admin/services'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutRecyclingRoute: typeof AboutRecyclingRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  HistoryRoute: typeof HistoryRoute
  ServicesRoute: typeof ServicesRoute
  AdminAboutRoute: typeof AdminAboutRoute
  AdminAboutRecyclingRoute: typeof AdminAboutRecyclingRoute
  AdminCareersRoute: typeof AdminCareersRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminGameRoute: typeof AdminGameRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-recycling': {
      id: '/about-recycling'
      path: '/about-recycling'
      fullPath: '/about-recycling'
      preLoaderRoute: typeof AboutRecyclingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/admin/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/admin/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/game': {
      id: '/admin/game'
      path: '/admin/game'
      fullPath: '/admin/game'
      preLoaderRoute: typeof AdminGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/admin/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/admin/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/about-recycling': {
      id: '/admin/about-recycling'
      path: '/admin/about-recycling'
      fullPath: '/admin/about-recycling'
      preLoaderRoute: typeof AdminAboutRecyclingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/admin/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutRecyclingRoute: AboutRecyclingRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  HistoryRoute: HistoryRoute,
  ServicesRoute: ServicesRoute,
  AdminAboutRoute: AdminAboutRoute,
  AdminAboutRecyclingRoute: AdminAboutRecyclingRoute,
  AdminCareersRoute: AdminCareersRoute,
  AdminContactRoute: AdminContactRoute,
  AdminGameRoute: AdminGameRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
